Repository Consensys/solc-typed-ast, pull requests merged in 2020-12, with the labels that each got.

#2 Mention project documentation in README
  README.md
Labels: documentation

#4 Fixes for ASTNodeFactory and TupleExpression
  src/ast/ast_node_factory.ts
  src/ast/implementation/expression/tuple_expression.ts
Labels: bug

#7 Add badges
  .drone.yml
  README.md
  package-lock.json
  package.json
Labels: documentation

#9 Option to include source code to compiler artifact
  src/bin/compile.ts
  test/integration/sol-ast-compile/common.ts
  test/integration/sol-ast-compile/with-source.spec.ts
Labels: enhancement

#10 Fix missing anonymous keyword when writing event definitions.
  src/ast/writing/ast_mapping.ts
  test/samples/solidity/writer_edge_cases.sol
  test/samples/solidity/writer_edge_cases.sourced.sol
Labels: bug

#12 Add support for Solidity 0.7.6 release
  package-lock.json
  package.json
  src/compile/constants.ts
  test/integration/compile/latest_07.spec.ts
  test/samples/solidity/latest_07.sol
  test/samples/solidity/latest_07.sourced.sol
Labels: enhancement
