Repository Consensys/solc-typed-ast, pull requests merged in 2021-04, with the labels that each got.

#26 Version change from 3.2.1 to 3.2.2
  package-lock.json
  package.json
Labels: pending release

#28 Version change from 3.2.2 to 4.0.0
  package-lock.json
  package.json
Labels: pending release

#29 Migrate some features from Scribble to solc-typed-ast
  package-lock.json
  src/ast/ast_node.ts
  src/ast/implementation/declaration/contract_definition.ts
  src/ast/index.ts
  src/ast/sanity.ts
  test/integration/factory/replace_node.spec.ts
Labels: enhancement

#30 A comprehensive list of known AST node types
  NODE_LIST.md
  README.md
Labels: documentation
