Repository Consensys/solc-typed-ast, pull requests merged in 2021-02, with the labels that each got.

#18 Version change from 3.1.0 to 3.2.0
  package-lock.json
  package.json
Labels: release

#19 Bug in the writing out of import directives
  src/ast/writing/ast_mapping.ts
  test/samples/solidity/meta/complex_imports/c.sourced.sol
Labels: bug

#21 Version change from 3.1.0 to 3.2.1
  package-lock.json
  package.json
Labels: pending release
