Repository Consensys/solc-typed-ast, pull requests merged in 2021-09, with the labels that each got.

#62 Version change from 6.1.0 to 6.1.1
  package-lock.json
  package.json
Labels: pending release

#63 Adopt internal types from Scribble
  src/types/ast/builtin_struct_type.ts
  src/types/ast/import_ref_type.ts
  src/types/ast/index.ts
  src/types/builtins.ts
  src/types/index.ts
  src/types/utils.ts
  test/unit/types/builtins.spec.ts
  test/unit/types/import_ref.spec.ts
Labels: enhancement

#67 bump to v6.1.2
  package-lock.json
  package.json
Labels: pending release

#64 Support composing getter/accessor types
  src/ast/implementation/declaration/enum_definition.ts
  src/misc/utils.ts
  src/types/utils.ts
  test/samples/solidity/getters_07.sol
  test/samples/solidity/getters_08.sol
  test/unit/ast/ast_node_factory/copy.spec.ts
  test/unit/ast/common.ts
  test/unit/misc/utils/assert.spec.ts
  test/unit/misc/utils/forAll.spec.ts
  test/unit/types/getters.spec.ts
Labels: enhancement

#71 Pretty printing
  src/misc/index.ts
  src/misc/node.ts
  src/misc/pretty_printing.ts
  src/misc/utils.ts
  test/unit/misc/pretty_printing.spec.ts
Labels: enhancement

#72 Version change from 6.1.3 to 6.1.4
  package-lock.json
  package.json
Labels: pending release

#70 Refactor getter typing logic and canonical signatures logic
  src/ast/definitions.ts
  src/ast/dispatch.ts
  src/ast/implementation/declaration/contract_definition.ts
  src/ast/implementation/declaration/error_definition.ts
  src/ast/implementation/declaration/event_definition.ts
  src/ast/implementation/declaration/function_definition.ts
  src/ast/implementation/declaration/modifier_definition.ts
  src/ast/implementation/declaration/variable_declaration.ts
  src/ast/implementation/expression/function_call.ts
  src/bin/compile.ts
  src/misc/struct_equality.ts
  src/types/abi.ts
  src/types/utils.ts
  test/samples/solidity/declarations/contract_050.nodes.txt
  test/samples/solidity/fun_selectors.tree.txt
  test/samples/solidity/getters_07_abiv1.sol
  test/samples/solidity/latest_08.nodes.txt
  test/samples/solidity/library_signatures.sol
  test/samples/solidity/resolving/struct_assignments.sol
  test/unit/ast/reading/declaration/contract_0413.spec.ts
  test/unit/ast/reading/declaration/contract_050.spec.ts
  test/unit/misc/struct_eq.spec.ts
  test/unit/types/getters.spec.ts
  test/unit/types/signatures.spec.ts
Labels: enhancement, breaking change

#73 Version change from 6.1.4 to 7.0.0
  package-lock.json
  package.json
  src/ast/definitions.ts
  src/ast/sanity.ts
  src/bin/compile.ts
  src/misc/pretty_printing.ts
  test/unit/misc/pretty_printing.spec.ts
Labels: pending release
