Repository Consensys/solc-typed-ast, pull requests merged in 2022-08, with the labels that each got.

#140 Remove sanity checking logic
  src/ast/index.ts
  src/ast/sanity.ts
  test/integration/factory/replace_node.spec.ts
Labels: breaking change

#145 bump to v10.1.6
  package-lock.json
  package.json
Labels: pending release

#146 Support for Solidity 0.8.16
  package-lock.json
  package.json
  src/compile/constants.ts
Labels: enhancement
