Repository Consensys/solc-typed-ast, pull requests merged in 2022-07, with the labels that each got.

#126 Support for Solidity 0.8.15
  package-lock.json
  package.json
  src/ast/implementation/declaration/error_definition.ts
  src/ast/implementation/declaration/event_definition.ts
  src/ast/implementation/declaration/function_definition.ts
  src/ast/implementation/declaration/modifier_definition.ts
  src/ast/implementation/declaration/variable_declaration.ts
  src/ast/sanity.ts
  src/ast/utils.ts
  src/bin/compile.ts
  src/compile/constants.ts
  test/integration/compile/latest_08.spec.ts
  test/integration/sol-ast-compile/tree.spec.ts
  test/integration/sourcemap/snapshot.spec.ts
  test/samples/solidity/interface_id.tree.txt
  test/samples/solidity/latest_08.nodes.native.txt
  test/samples/solidity/latest_08.nodes.wasm.txt
  test/samples/solidity/latest_08.sol
  test/samples/solidity/latest_08.sourced.sol
  test/samples/solidity/selectors.sol
  test/samples/solidity/selectors.tree.txt
  test/unit/ast/utils.spec.ts
Labels: enhancement

#127 Version change from 10.1.2 to 10.1.3
  package-lock.json
  package.json
Labels: pending release

#129 Fix GitHub Actions to correctly publish docs and package
  .github/workflows/docs.yaml
  .github/workflows/npm.yaml
Labels: bug

#133 Fix for #132
  src/ast/legacy/function_definition_processor.ts
  src/ast/modern/function_definition_processor.ts
  src/ast/utils.ts
  test/integration/factory/copy.spec.ts
  test/samples/solidity/issue_132_fun_kind.nodes.native.txt
  test/samples/solidity/issue_132_fun_kind.nodes.wasm.txt
  test/samples/solidity/issue_132_fun_kind.sol
Labels: bug

#134 Create GitHub action to publish Docker image
  .github/workflows/docker_image.yaml
  README.md
  docker/Dockerfile
Labels: enhancement

#138 Tweak `eq()` to do an early return if `a` and `b` are strictly equal
  package-lock.json
  package.json
  src/misc/struct_equality.ts
  test/unit/misc/struct_eq.spec.ts
Labels: enhancement

#139 Version change from 10.1.4 to 10.1.5
  package-lock.json
  package.json
Labels: pending release
