Repository Consensys/solc-typed-ast, pull requests merged in 2022-05, with the labels that each got.

#120 Version change from 10.0.0 to 10.1.0
  package-lock.json
  package.json
Labels: pending release

#121 File remapping nit
  package.json
  src/compile/utils.ts
Labels: bug

#122 Version change from 10.1.0 to 10.1.1
  package-lock.json
  package.json
Labels: pending release

#123 Support for Solidity 0.8.14
  package-lock.json
  package.json
  src/compile/constants.ts
Labels: enhancement

#125 Version change from 10.1.1 to 10.1.2
  package-lock.json
  package.json
Labels: pending release
