Repository Consensys/solc-typed-ast, pull requests merged in 2022-02, with the labels that each got.

#89 Docker image with downloaded prerequisites
  docker/Dockerfile
  docker/download.sh
Labels: enhancement

#91 Version change from 7.2.0 to 8.0.0
  package-lock.json
  package.json
Labels: pending release

#93 Cleanup import resolution logic
  src/compile/inference/imports.ts
  src/compile/input.ts
  src/compile/utils.ts
  test/integration/compile/kinds.spec.ts
  test/samples/solidity/path_remapping/node_modules/@package/contracts/package_contract.sol
  test/samples/solidity/path_remapping/node_modules/@package/contracts/package_lib.sol
  test/unit/compile/inference/findAllFiles.spec.ts
Labels: bug

#94 Version change from 8.0.0 to 8.0.1
  package-lock.json
  package.json
Labels: pending release

#95 Predownload native compilers in CI
  .drone.yml
Labels: enhancement

#92 Dowloading WASM compilers on-demand instead of preinstalling from NPM
  .drone.yml
  docker/Dockerfile
  docker/download.sh
  package-lock.json
  package.json
  src/compile/constants.ts
  src/compile/input.ts
  src/compile/kinds/compiler.ts
  src/compile/kinds/index.ts
  src/compile/kinds/md.ts
  src/compile/kinds/native.ts
  src/compile/kinds/wasm.ts
  src/compile/utils.ts
  src/types/builtins.ts
  test/integration/compile/latest_08.spec.ts
  test/integration/sourcemap/solc_comparison.spec.ts
  test/samples/solidity/latest_08.nodes.native.txt
  test/samples/solidity/latest_08.nodes.wasm.txt
  test/samples/solidity/latest_08.sol
  test/samples/solidity/latest_08.sourced.sol
  test/unit/compile/utils.spec.ts
  test/unit/misc/definitions.spec.ts
Labels: enhancement, breaking change
