Repository Consensys/solc-typed-ast, pull requests merged in 2022-03, with the labels that each got.

#97 Migrate to NodeJS 16 LTS
  .drone.yml
  README.md
  docker/Dockerfile
  docker/download.sh
  package-lock.json
  package.json
  src/bin/compile.ts
  src/compile/kinds/compiler.ts
  src/compile/kinds/md.ts
  test/integration/sol-ast-compile/common.ts
  test/integration/sol-ast-compile/locate-compiler-cache.spec.ts
  test/integration/sol-ast-compile/with-source.spec.ts
Labels: enhancement

#98 Implement parser for rational literal types
  src/types/ast/index.ts
  src/types/ast/rational_literal.ts
  src/types/typeStrings/typeString_grammar.pegjs
  src/types/typeStrings/typeString_parser_header.ts
  test/samples/solidity/types/types.sol
Labels: enhancement

#101 Redownload compiler metadata file
  package.json
  src/compile/kinds/compiler.ts
  src/compile/kinds/md.ts
  src/types/ast/rational_literal.ts
Labels: enhancement

#102 Version change from 9.0.0 to 9.0.1
  package-lock.json
  package.json
Labels: pending release

#104 Support function types in ABI-related logic
  src/types/abi.ts
  test/samples/solidity/library_signatures.sol
  test/samples/solidity/signatures.sol
  test/unit/types/signatures.spec.ts
Labels: bug

#105 Support multiple file inputs to `compileSol()`
  src/bin/compile.ts
  src/compile/import_resolver.ts
  src/compile/inference/imports.ts
  src/compile/input.ts
  src/compile/utils.ts
  test/integration/sol-ast-compile/mode/valid.spec.ts
  test/integration/sol-ast-compile/tree.spec.ts
  test/samples/solidity/multifile/A.sol
  test/samples/solidity/multifile/A_B.tree.txt
  test/samples/solidity/multifile/A_B_C.tree.txt
  test/samples/solidity/multifile/A_C.tree.txt
  test/samples/solidity/multifile/B.sol
  test/samples/solidity/multifile/C.sol
  test/samples/solidity/multifile/node_modules/package-x/contracts/X.sol
  test/samples/solidity/multifile/node_modules/package-y/contracts/Y.sol
  test/unit/compile/inference/findAllFiles.spec.ts
Labels: enhancement

#107 Support for Solidity 0.8.13
  package-lock.json
  package.json
  src/ast/ast_node_factory.ts
  src/ast/implementation/meta/source_unit.ts
  src/ast/implementation/meta/using_for_directive.ts
  src/ast/implementation/statement/inline_assembly.ts
  src/ast/legacy/inline_assembly_processor.ts
  src/ast/legacy/using_for_directive_processor.ts
  src/ast/modern/inline_assembly_processor.ts
  src/ast/modern/using_for_directive_processor.ts
  src/ast/sanity.ts
  src/ast/writing/ast_mapping.ts
  src/compile/constants.ts
  src/compile/inference/file_level_definitions.pegjs
  src/compile/inference/file_level_definitions_parser_header.ts
  test/integration/compile/latest_08.spec.ts
  test/samples/solidity/declarations/contract_050.nodes.native.txt
  test/samples/solidity/declarations/contract_050.nodes.wasm.txt
  test/samples/solidity/latest_08.nodes.native.txt
  test/samples/solidity/latest_08.nodes.wasm.txt
  test/samples/solidity/latest_08.sol
  test/samples/solidity/latest_08.sourced.sol
  test/unit/ast/reading/meta/using_for.spec.ts
  test/unit/compile/inference/file_level_definitions_parser.spec.ts
Labels: enhancement, breaking change

#108 Version change from 9.0.1 to 9.1.0
  package-lock.json
  package.json
Labels: pending release

#109 Return remappings inferred by the `LocalNpmResolver` in the `CompileResult`
  src/compile/import_resolver.ts
  src/compile/utils.ts
  test/unit/compile/import_resolver.spec.ts
Labels: enhancement

#112 Fix for #111
  src/ast/definitions.ts
  test/unit/misc/definitions.spec.ts
Labels: bug

#113 Version change from 9.1.1 to v9.1.2
  package-lock.json
  package.json
Labels: pending release
