Repository Consensys/solc-typed-ast, pull requests merged in 2024-01, with the labels that each got.

#245 Update dependencies
  package-lock.json
  package.json
  src/ast/ast_node_factory.ts
Labels: dependencies

#242 Switch sources to typed arrays instead of strings
  .eslintrc.json
  .gitignore
  .nycrc.json
  package.json
  src/ast/ast_node.ts
  src/ast/ast_reader.ts
  src/ast/comments/comment.ts
  src/ast/comments/comments_grammar.pegjs
  src/ast/comments/comments_parser_header.ts
  src/ast/comments/index.ts
  src/ast/constants.ts
  src/ast/index.ts
  src/ast/postprocessing/structured_documentation_reconstruction.ts
  src/ast/writing/ast_mapping.ts
  src/ast/writing/writer.ts
  src/bin/compile.ts
  src/compile/compiler_selection.ts
  src/compile/inference/imports.ts
  src/compile/input.ts
  src/compile/utils.ts
  src/misc/index.ts
  src/misc/unicode.ts
  test/integration/compile/04.spec.ts
  test/integration/compile/05.spec.ts
  test/integration/compile/06.spec.ts
  test/integration/compile/kinds.spec.ts
  test/integration/compile/latest_06.spec.ts
  test/integration/compile/latest_07.spec.ts
  test/integration/compile/latest_08.spec.ts
  test/integration/sol-ast-compile/xpath/struct_doc_recovery.spec.ts
  test/samples/solidity/struct_doc_recovery.sol
  test/samples/solidity/struct_docs_04.sourced.sol
  test/samples/solidity/struct_docs_05.sourced.sol
  test/samples/solidity/unicode.sol
  test/samples/solidity/unicode_big.sol
  test/unit/ast/ast_node.spec.ts
  test/unit/ast/unicode.spec.ts
  test/unit/compile/compiler_selection.spec.ts
  test/unit/compile/inference/findAllFiles.spec.ts
  test/unit/compile/utils.spec.ts
  tsconfig.json
Labels: bug, enhancement, breaking change

#247 Version change from 17.0.3 to 18.0.0
  .vscode/settings.json
  package-lock.json
  package.json
Labels: pending release

#251 Version change from 18.0.0 to 18.1.0
  package-lock.json
  package.json
Labels: pending release
